app = "bxc-backend" # IMPORTANT: Use the app name you chose during flyctl launch!
primary_region = "ams" # Replace with your preferred region (e.g., ams, lhr, iad)

# Remove the [build] section entirely if you are using a Dockerfile.
# If you didn't have a Dockerfile, then the builder line would be useful.
# But since you have a Dockerfile, Fly.io will use it by default.

[env]
  # Any other environment variables your app needs can go here,
  # but sensitive ones like MONGODB_URI should be set as secrets.

[http_service]
  internal_port = 5000 # Make sure this matches the PORT your app listens on (process.env.PORT)
  force_https = true
  auto_stop_machines = true  # CORRECTED: Should be boolean true
  auto_start_machines = true # CORRECTED: Should be boolean true
  min_machines_running = 1 # Keep at least one machine running for responsiveness
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
